#!/bin/sh

# Stop and remove all running containers
CONTAINERS=$(docker ps -q)
if [ "${CONTAINERS}" != "" ]; then
    docker stop ${CONTAINERS}
    docker rm ${CONTAINERS}
fi

# Prepare the build directory and move inside it
cp -r install-data/* .

# Start the containers and create the project
docker-compose up -d
docker-compose run --rm app composer create-project "symfony/skeleton" tmp --prefer-dist --no-progress --no-interaction

# Clear the temporary project files
cp -rf tmp/. . && rm -Rf tmp

# Install some common dependencies
docker-compose run --rm app composer req orm asset security translation form encore validator twig asset annot
docker-compose run --rm app composer req --dev debug-pack
docker-compose run --rm app npm install --save jquery sass-loader node-sass

# Run make build on the project
make build

# Remove the installer data
rm -rf .git install-data install README.md
