#!/bin/sh

# Stop and remove all running containers
CONTAINERS=$(docker ps -q)
if [ "${CONTAINERS}" != "" ]; then
    docker stop ${CONTAINERS}
    docker rm ${CONTAINERS}
fi

# Copy the installation data into the build directory
# If the .git directory exists, this means we're developing the installer,
# otherwise we're using the installer to boot a new project.
if [ -d "./.git" ]; then
    mkdir -p "./test"
    cp -r install-data/* "./test"
    cd "./test"
else
    rm -f README.md .gitignore
    cp -r install-data/* .
fi

# Create the project
docker-compose run --rm app composer create-project "symfony/skeleton" tmp --prefer-dist --no-progress --no-interaction
cp -rf tmp/. . && rm -Rf tmp

# Install some common dependencies
docker-compose run --rm app composer req orm annot security translation form validator twig asset encore
docker-compose run --rm app composer req --dev debug-pack
docker-compose run --rm app npm install --save jquery sass-loader node-sass

# Run make build on the project
make build

# Remove the installer data
rm -rf install-data install
