#!/bin/sh

# Stop and remove all running containers
CONTAINERS=$(docker ps -q)
if [ "${CONTAINERS}" != "" ]; then
    docker stop ${CONTAINERS}
    docker rm ${CONTAINERS}
fi

# Copy the installation data into the build directory
if [ "$1" != "" ]; then
    mkdir -p "./$1"
    cp -r install-data/* "./$1"
    cd "./$1"
else
    cp -r install-data/* .
fi

# Create the project
# docker-compose up -d
docker-compose run --rm app composer create-project "symfony/skeleton" tmp --prefer-dist --no-progress --no-interaction
cp -rf tmp/. . && rm -Rf tmp

# Install some common dependencies
docker-compose run --rm app composer req orm asset security translation form encore validator twig asset annot
docker-compose run --rm app composer req --dev debug-pack
docker-compose run --rm app npm install --save jquery sass-loader node-sass

# Run make build on the project
make build

# Remove the installer data
rm -rf .git install-data install README.md
